#+title: Exploring Kubernetes Prow Jobs
#+PROPERTY: header-args:sql-mode+ :product postgres
* Intoduction
Infrasnoop is a work-in-progress db customized for querying kubernetes prow jobs.
This org file acts as a starting template for building out your own explorations into the code.
* Getting started
If you are running this in a coder workspace, then the db is likely already
running in the background. We can test it with this code block. Navigate your
cursor to the below code block and hit enter to run. It will prompt you for the
server and db, accept the defaults each time by hitting enter.


#+begin_src sql-mode
select * from describe_relations();
#+end_src


** Important! Load up the data
The query shows us the tables and views available in our two schemas "sigs" and "prow".  Neither of these have data yet, but we can load them up
with these two respective functions

#+begin_src sql-mode :results silent
select * from load_sigs_tables();
#+end_src


#+begin_src sql-mode
select * from add_prow_deck_jobs();
#+end_src

After running, our app in the background will look at the latest successful runs
and, for each of these jobs, grab their prowjob definition (e.g. their
prowjob.yaml). It takes about a minute to load, but once ready you can look at
the raw data in the table ~prow.job~.

#+begin_src sql-mode
select count(*) from prow.job;
#+end_src

You can run the above code block multiple times and you'll see the count go up
as the sideloader works. When it is no longer adding new jobs, the database is
ready to explore.

* Looking at prow jobs further

Let's look at the prow.job table

#+begin_src sql-mode
select * from describe_columns('prow','job');
#+end_src

It is simple, with the main interestin being the data column.  This is a jsonb column, So any [[https://duckduckgo.com/?t=ffab&q=postgres+operator&ia=web][postgres jsonb operator]] can be used to explore it.

In addition, we've taken some of the relevant parts of the job and turned them into their own views: prow.job_spec, prow.job_label, and prow.job_annotation.

the spec is taken from the spec key in the prow.job
#+begin_src sql-mode
\d prow.job_spec;
#+end_src

while the label and annotations is taken from metadata.labels and metadata.annotations, respectively.
#+begin_src sql-mode
\d prow.job_label;
#+end_src

#+begin_src sql-mode
\d prow.job_annotation;
#+end_src

* Example prow queries
** A sanity check
First, let's look at a prow job that we know should exist in our successful jobs: the apisnoop conformance-gate.

#+begin_src sql-mode
select job
  from prow.job
 where job ilike '%apisnoop%conformance%';
#+end_src

And we can see when this job ran.

#+begin_src sql-mode
select job.job, started, finished
  from prow.deck deck
         join prow.job job using(build_id)
 where job.job = 'apisnoop-conformance-gate';
#+end_src

And some details on its spec.

#+begin_src sql-mode
select job, type, agent, cluster, prowjob_defaults, namespace
  from prow.job_spec
 where job = 'apisnoop-conformance-gate';
#+end_src


We can look at its labels
#+begin_src sql-mode
select label,content
  from prow.job_label
 where job = 'apisnoop-conformance-gate';
#+end_src

And its annotations:

#+begin_src sql-mode
select annotation, content
  from prow.job_annotation
 where job = 'apisnoop-conformance-gate';
#+end_src

If all the above queries returned results, then our db is set up and connected and good. Now we can do some more interesting queries.

** Jobs without a cluster
This query will show any successfully running jobs that have no cluster defined in their spec.  Ideally this number is low, and this may even return 0 results.

#+begin_src sql-mode
select job
  from prow.job
       join prow.job_spec spec using(job)
 where spec.cluster is null;
#+end_src

When I last ran it, I got 3 results returned.

** Jobs with dind-enabled

One other thing we could look at is the number of jobs labelled with 'preset-dind-enabled'.
#+begin_src sql-mode
select count(job)
  from prow.job_label
 where label = 'preset-dind-enabled';
#+end_src

This will be many more, likely, so I just asked for the count.

you can always dive deeper by looking at the results, but limit to 25 rows or some other limit.


*** look at all the other labels of these jobs
For the jobs labelled with 'preset-dind-enabled', what other labels do they have?

one way to ask this is to use a common table expression(cte):

#+begin_src sql-mode
with dind_jobs as (
  select job
    from prow.job_label
   where label = 'preset-dind-enabled'
)
select job, label, content
  from prow.job j
       join prow.job_label l using(job)
       join dind_jobs d using(job)
 order by j.job, label
 limit 25 ;
#+end_src

We can do a frequency count for the types of labels (note: this prolly isn't an interesting query, but useful for showing some sql tricks)

#+begin_src sql-mode
with dind_jobs as (
  select job
    from prow.job_label
   where label = 'preset-dind-enabled'
)
select distinct label, count(distinct job)
  from prow.job j
       join prow.job_label l using(job)
       join dind_jobs d using(job)
              group by label
 order by count desc
 limit 50;
#+end_src


* Looking into the jobs without a cluster
Before, we found the cluster-free jobs with

#+begin_src sql-mode
select job
  from prow.job_spec spec
 where spec.cluster is null
 group by job;
#+end_src

this returns some # of jobs(usually 3-9)


However, this is a bit misleading. They're "spec.cluster" value is null, but it's because there is no spec! We can see this when we try to look at the raw data.

#+begin_src sql-mode
select job, data
  from prow.job
       join prow.job_spec spec using(job)
 where spec.cluster is null;
#+end_src

It's spec is just the note "ProwJob not found".

This bit of json is being pulled direct from their spyglass link, which we can grab with the below query

#+begin_src sql-mode
select job, url
  from prow.job
       join prow.job_spec spec using(job)
       join prow.deck using(job,build_id)
 where spec.cluster is null;
#+end_src


Zooming out, we can organize all the successful jobs by the clusters they use.
The row at the bottom will be for the null clusters, e.g. without prowjob
definitions.

#+begin_src sql-mode
select cluster, count(*)
  from prow.job_spec
 group by cluster
 order by count desc;
#+end_src

Is there any pattern that connects these jobs without prowjobs?

* Footnotes
#+REVEAL_ROOT: https://multiplex.ii.nz
#+NOREVEAL_MULTIPLEX_SECRET: 16830253579594699605
#+NOREVEAL_MULTIPLEX_ID: f0343d4424c81b11
#+OPTIONS: toc:nil
** TODO export via clicking
** setup index.html as default
#+begin_src shell :results silent
# ln -sf ii_client.html index.html
ln -sf ii.html index.html
#+end_src
** start up a webserver
#+name: http.server
#+begin_src tmux :session ":http"
python3 -m http.server
#+end_src
