#!/bin/bash
set -x
export DEBIAN_FRONTEND=noninteractive
until kubectl version --client; do
        sleep 5
        apt-fast \
                -o Dpkg::Options::="--force-confdef" \
                -o Dpkg::Options::="--force-confold" install -y \
                docker-ce \
                docker-ce-cli \
                kubelet \
                kubeadm \
                helm
done
swapoff -a # not compatible with Kubernetes
kubeadm config images pull
kubeadm init --config /etc/kubernetes/kubeadm-config.yaml # install k8s
export KUBECONFIG=/etc/kubernetes/admin.conf
mkdir -p /root/.kube
ln -sf $KUBECONFIG /root/.kube/config
mkdir -p /home/${username}/.kube
cp -i $KUBECONFIG /home/${username}/.kube/config
chown -R ${username}:${username} /home/${username}/.kube
# Wait until k8s in up
until kubectl get --raw='/readyz?verbose'; do sleep 5; done
# Untaint the node so we can schedule workloads
# TODO: Deploy without taints
kubectl taint nodes --all node-role.kubernetes.io/control-plane:NoSchedule-
# Deploy cilium and iipod / apisnoop
# Would be nice if these were automatically static pods
# kubectl apply -f /etc/kubernetes/manifests/cilium.yaml
# TODO: Maybe crictl to pull this down BEFORE k8s is installed
kubectl apply -f /etc/kubernetes/manifests/iipod.yaml
kubectl apply -f /etc/kubernetes/manifests/istio.yaml
kubectl apply -f /etc/kubernetes/manifests/apisnoop.yaml
kubectl apply -f /etc/kubernetes/manifests/cert-manager.yaml
# kubectl apply -f /etc/kubernetes/manifests/snoopdb.yaml
# kubectl apply -f /etc/kubernetes/manifests/auditlogger.yaml
# We need to add the current primary public ip without metallb
# so "LoadBalancer" type loads this as the ip
IP=$(cloud-init query -f "{{ds.meta_data.public_ipv4}}")
cat <<EOF >>/etc/kubernetes/manifests/nginx.yaml
  values:
    controller:
      extraArgs:
        default-ssl-certificate: "ingress-nginx/wildcard-tls"
      service:
        externalIPs:
          - $IP
EOF
kubectl apply -f /etc/kubernetes/manifests/nginx.yaml
kubectl -n ingress-nginx create secret tls wildcard-tls \
        --cert=/etc/cloud/wildcard.cert.pem \
        --key=/etc/cloud/wildcard.key.pem
