#!/bin/bash
set -x
export DEBIAN_FRONTEND=noninteractive
until kubectl version --client; do
        sleep 5
        apt-fast \
                -o Dpkg::Options::="--force-confdef" \
                -o Dpkg::Options::="--force-confold" install -y \
                docker-ce \
                docker-ce-cli \
                kubelet \
                kubeadm \
                helm
done
swapoff -a # not compatible with Kubernetes
kubeadm config images pull
kubeadm init --config /etc/kubernetes/kubeadm-config.yaml # install k8s
export KUBECONFIG=/etc/kubernetes/admin.conf
mkdir -p /root/.kube
ln -sf $KUBECONFIG /root/.kube/config
mkdir -p /home/${username}/.kube
cp -i $KUBECONFIG /home/${username}/.kube/config
chown -R ${username}:${username} /home/${username}/.kube
# Wait until k8s in up
until kubectl get --raw='/readyz?verbose'; do sleep 5; done
# Untaint the node so we can schedule workloads
# TODO: Deploy without taints
kubectl taint nodes --all node-role.kubernetes.io/control-plane:NoSchedule-
# Deploy cilium and iipod / apisnoop
# Would be nice if these were automatically static pods
# kubectl apply -f /etc/kubernetes/manifests/cilium.yaml
# TODO: Maybe crictl to pull this down BEFORE k8s is installed
kubectl apply -f /etc/kubernetes/manifests/iipod.yaml
