#!/bin/bash
git clone --depth 1 https://github.com/doomemacs/doomemacs ~/.config/emacs
git clone --depth 1 https://github.com/ii/doom-config ~/.config/doom
yes | ~/.config/emacs/bin/doom install --env --fonts
