#!/bin/bash
# Base Packages... install these first
export DEBIAN_FRONTEND=noninteractive
export NEEDRESTART_MODE=a
export KUBECONFIG=/etc/kubernetes/admin.conf
apt-fast \
    -o Dpkg::Options::="--force-confdef" \
    -o Dpkg::Options::="--force-confold" \
    install -y \
    emacs-gtk \
    kitty \
    novnc \
    websockify \
    postgresql-client \
    tigervnc-standalone-server \
    asciinema \
    silversearcher-ag \
    direnv \
    whowatch \
    aptitude \
    jq

# Give Kubernetes a chance to install / be ready
until kubectl get --raw='/readyz?verbose'; do sleep 5; done

# now loop here, tryingto intall everything needed for desktop
until gnome-session --version; do
    sleep 5
    apt-fast \
        -o Dpkg::Options::="--force-confdef" \
        -o Dpkg::Options::="--force-confold" \
        install -y \
        apache2-utils \
        inotify-tools \
        xtermcontrol \
        unzip \
        rlwrap \
        fonts-powerline \
        tree \
        iftop \
        ripgrep \
        locate \
        fd-find \
        python-is-python3 \
        gettext-base \
        graphviz \
        golang-1.20 \
        google-chrome-stable \
        ubuntu-desktop \
        pipenv \
        python3-pip \
        openjdk-17-jdk \
        screenkey \
        code \
        gvfs \
        dbus-x11
    # We need to update-alternatives for go
    update-alternatives --install /usr/bin/go go /usr/lib/go-1.20/bin/go 50 --slave /usr/bin/gofmt gofmt /usr/lib/go-1.20/bin/gofmt
    # Ideally we don't install these at all
    # We don't need them
    apt-get \
        remove -y --autoremove \
        gnome-initial-setup \
        thunderbird \
        rhythmbox -y
done
# gh / aws / gcloud commands
until gh --version; do
    sleep 5
    apt-fast \
        -o Dpkg::Options::="--force-confdef" \
        -o Dpkg::Options::="--force-confold" \
        install -y \
        gh \
        awscli \
        google-cloud-sdk
done
apt-get \
    upgrade -y
